### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by Tostino** [kamalkraj/e5-mistral-7b-instruct#1]
I tried to use your script, but cannot get it going. Using 2x 3090.

Only change is adding some debug prints so I could try and figure out what was going on, and lowering gradient accumulation.

```
Traceback (most recent call last):
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/peft_lora_embedding_semantic_search.py", line 554, in <module>
    main()
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/peft_lora_embedding_semantic_search.py", line 480, in main
    sentence_embs = model(**{k.replace("sentence_", ""): v for k, v in batch.items() if "sentence" in k})
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/deepspeed/runtime/engine.py", line 1833, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/peft/peft_model.py", line 1849, in forward
    return self.base_model(
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 100, in forward
    return self.model.forward(*args, **kwargs)
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/peft_lora_embedding_semantic_search.py", line 217, in forward
    transformer_outputs = self.model(
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/transformers/models/mistral/modeling_mistral.py", line 1001, in forward
    attention_mask = _prepare_4d_causal_attention_mask_for_sdpa(
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/transformers/modeling_attn_mask_utils.py", line 409, in _prepare_4d_causal_attention_mask_for_sdpa
    expanded_4d_mask = AttentionMaskConverter._unmask_unattended(
  File "/home/user/IdeaProjects/e5-mistral-7b-instruct/venv/lib/python3.10/site-packages/transformers/modeling_attn_mask_utils.py", line 253, in _unmask_unattended
    range_tensor[range_tensor >= indices] = 0
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

Same thing happens if I try and use just python to launch without deepspeed.

**Comment by kamalkraj** [comment]
Hi,

Could you share the content of `ds_zero3_cpu.yaml`

**Comment by Tostino** [comment]
Sure thing:
```
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_accumulation_steps: 8
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

**Comment by kamalkraj** [comment]
Try with this config
```compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_accumulation_steps: 8
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

**Comment by Tostino** [comment]
Same exact error.

**Comment by kamalkraj** [comment]
You trying in docker or local env.

**Comment by Tostino** [comment]
Sorry, was doing this in local env (venv). The docker env is unavailable for me because I use rancher desktop: https://github.com/rancher-sandbox/rancher-desktop/issues/3968#issuecomment-1502624799 (yes, I installed nvidia-container-toolkit, didn't help).
```
(venv) user@pop-os:~/IdeaProjects/e5-mistral-7b-instruct$ sudo docker run --gpus=all --ipc=host --ulimit memlock=-1 --ulimit stack=67108864 -it --rm -v $(pwd):/e5-mistral-7b-instruct/ pytorch bash
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
```

Though I haven't had any issues training models with Axolotl or Tevatron in this local environment.

Edit:
OS: Pop!_OS 22.04 LTS
Nvidia driver: 545.29.06

**Comment by kamalkraj** [comment]
Could you try with `podman`

**Comment by Tostino** [comment]
Nope, after spending a couple of hours on it...not happening without just installing another OS on a different partition. I need rancher desktop for other workloads, and unless I purge that entirely, I just can't get Podman playing nice.

Oh well.

**Comment by Tostino** [comment]
I went and spent the time setting up a new environment. After figuring out that podman with ubuntu 22.04 lts is an extremely old version, and that I needed to install a new apt repo to get a recent version, things are working. Training works fine in the container.
