### ISSUE TITLE
when I modify batch_size larger than 1

### ISSUE THREAD

**Issue by sangzisen** [kamalkraj/e5-mistral-7b-instruct#3]
batch[k] = torch.tensor([f[k] for f in features])
ValueError: expected sequence of length 37 at dim 1 (got 40)

It's seems like that the default_data_collator has some problem

**Comment by kamalkraj** [comment]
Please share full logs and reproducible steps

**Comment by sangzisen** [comment]
File "/opt/conda/envs/python3.8.13/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/root/.local/lib/python3.8/site-packages/transformers/data/data_collator.py", line 70, in default_data_collator
    return torch_default_data_collator(features)
  File "/root/.local/lib/python3.8/site-packages/transformers/data/data_collator.py", line 136, in torch_default_data_collator
    batch[k] = torch.tensor([f[k] for f in features])
ValueError: expected sequence of length 75 at dim 1 (got 81)

**Comment by kamalkraj** [comment]
Please share full logs

**Comment by Rinatum** [comment]
To reproduce 

* config:
```
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  gradient_accumulation_steps: 2048
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: true
  zero3_save_16bit_model: true
  zero_stage: 3
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

* Run params:

```
accelerate launch     --config_file ds_zero3_gpu.yaml     peft_lora_embedding_semantic_search.py     --dataset_name similarity_dataset     --max_length 512     --model_name_or_path intfloat/e5-mistral-7b-instruct     --per_device_train_batch_size 2     --per_device_eval_batch_size 2     --learning_rate 0.0001     --weight_decay 0.01     --max_train_steps 1000     --gradient_accumulation_steps 2048     --lr_scheduler_type linear     --num_warmup_steps 100     --output_dir trained_model     --use_peft
```

* Full logs:

```
Traceback (most recent call last):
  File "/home/jovyan/Code/e5-mistral-7b-instruct/peft_lora_embedding_semantic_search.py", line 545, in <module>
    main()
  File "/home/jovyan/Code/e5-mistral-7b-instruct/peft_lora_embedding_semantic_search.py", line 469, in main
    for step, batch in enumerate(active_dataloader):
  File "/home/jovyan/.local/lib/python3.10/site-packages/accelerate/data_loader.py", line 451, in __iter__
    current_batch = next(dataloader_iter)
  File "/home/jovyan/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/jovyan/.local/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/jovyan/.local/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/jovyan/.local/lib/python3.10/site-packages/transformers/data/data_collator.py", line 92, in default_data_collator
    return torch_default_data_collator(features)
  File "/home/jovyan/.local/lib/python3.10/site-packages/transformers/data/data_collator.py", line 158, in torch_default_data_collator
    batch[k] = torch.tensor([f[k] for f in features])
ValueError: expected sequence of length 503 at dim 1 (got 276)
[2024-02-02 13:19:15,678] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 14387) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/home/jovyan/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/jovyan/.local/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
    args.func(args)
  File "/home/jovyan/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1008, in launch_command
    deepspeed_launcher(args)
  File "/home/jovyan/.local/lib/python3.10/site-packages/accelerate/commands/launch.py", line 724, in deepspeed_launcher
    distrib_run.run(args)
  File "/home/jovyan/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/jovyan/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/jovyan/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
peft_lora_embedding_semantic_search.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-02_13:19:15
  host      : musing-chandrasekhar-0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 14387)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

**Comment by kamalkraj** [comment]
@Rinatum 
Not able to reproduce the issue. Please try running the code in Docker

Suppose you are using a different dataset. Please share that also.

**Comment by Rinatum** [comment]
@kamalkraj 

The main problem that there is no flexible collate function and if you will run your code with batch size > 1 on custom dataset with sequences of different lenghts your code will be fail because of collate. I solved this problem using custom collator, I can share the code if you want

**Comment by kamalkraj** [comment]
@Rinatum 
Please raise a PR to fix the issue. 

Could you share a sample dataset to reproduce the issue?

**Comment by sangzisen** [comment]
I solved the problem by a custom data collator_fn, and move data preprocess to collator_fn.
